#!/usr/bin/env bash
# ============================================
#  ARTEMIS CITY - SECRET SETUP SCRIPT
# ============================================
# Generates fresh keys and populates the four env files used across the
# repo, each in the location its consumer expects:
#
#   .env                                       Python core (orchestrator,
#                                              memory bus, registry, FastAPI
#                                              dashboard in app/api/main.py)
#   app/api/.env                               TypeScript Express API
#                                              (app/api/index.ts and routes)
#   src/.env                                   Legacy / memory-layer Python
#   src/Artemis Agentic Memory Layer/.env      Memory-layer MCP server
#                                              (if the directory exists)
#
# Generated keys:
#   MCP_API_KEY              shared MCP / FastAPI auth (matches across files)
#   FASTAPI_API_KEY          FastAPI dashboard (app/api/main.py)
#   ARTEMIS_API_KEY_DEFAULT  TS Express admin key (key:role:perms tuple)
#   REDIS_PASSWORD           Redis password for docker-compose.yml
#   QDRANT_API_KEY           Vector store API key for docker-compose.yml
#   GRAFANA_PASSWORD         Grafana admin password for docker-compose.yml
#
# Usage: ./setup_secrets.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

generate_key() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        python3 -c "import secrets; print(secrets.token_hex(32))"
    fi
}

# sed -i is portable when called via this wrapper.
inplace_sed() {
    local script="$1" file="$2"
    if [[ "${OSTYPE:-}" == "darwin"* ]]; then
        sed -i '' "$script" "$file"
    else
        sed -i "$script" "$file"
    fi
}

# Substitute a placeholder with a value in a file. Skips silently when the
# placeholder is absent (file may legitimately not declare that key).
set_value() {
    local placeholder="$1" value="$2" file="$3"
    if grep -q "$placeholder" "$file" 2>/dev/null; then
        local escaped
        escaped=$(printf '%s' "$value" | sed -e 's/[\/&]/\\&/g')
        inplace_sed "s/$placeholder/$escaped/g" "$file"
    fi
}

# Set KEY=value in an env file, appending it when absent. This is used for
# deployment variables that are consumed by docker-compose.yml but are not
# present in every historical .env.example.
set_env_var() {
    local key="$1" value="$2" file="$3"
    local escaped
    escaped=$(printf '%s' "$value" | sed -e 's/[\/&]/\\&/g')

    if grep -Eq "^#?${key}=" "$file" 2>/dev/null; then
        inplace_sed "s/^#\?${key}=.*/${key}=${escaped}/" "$file"
    else
        printf '%s=%s\n' "$key" "$value" >> "$file"
    fi
}

# Prompt before overwriting an existing file. Returns 0 to proceed.
should_write() {
    local target="$1"
    if [[ ! -f "$target" ]]; then
        return 0
    fi
    echo -e "${YELLOW}!${NC}  $target already exists"
    read -p "   Overwrite? (y/N): " -r reply
    [[ "$reply" =~ ^[Yy]$ ]]
}

# Add the deployment variables documented in docs/DEPLOYMENT.md to the root
# .env. Docker Compose reads this file directly for required secrets, while the
# Python services can also consume the ARTEMIS_* settings during production
# runs.
add_root_deployment_env() {
    local target="$1"

    cat >> "$target" <<'EOF'

# ============================================
# 🚀 DEPLOYMENT / DOCKER COMPOSE CONFIGURATION
# ============================================
# Generated by setup_secrets.sh from docs/DEPLOYMENT.md defaults.
# docker-compose.yml reads this root .env file for required service secrets.
EOF

    # Public service auth consumed by docker-compose.yml / express-api.
    set_env_var "ARTEMIS_API_KEY_DEFAULT" "${TS_KEY}:admin:read,write,delete,admin" "$target"

    # Deployment environment
    set_env_var "ARTEMIS_LOG_LEVEL" "INFO" "$target"

    # Service URLs
    set_env_var "ARTEMIS_KERNEL_URL" "http://kernel:8000" "$target"
    set_env_var "ARTEMIS_REGISTRY_URL" "http://registry:8002" "$target"
    set_env_var "ARTEMIS_MEMORY_BUS_URL" "http://memory-bus:8001" "$target"

    # Storage
    set_env_var "ARTEMIS_OBSIDIAN_VAULT_PATH" "/data/vault" "$target"
    set_env_var "ARTEMIS_VECTOR_STORE_URL" "http://vector-store:6333" "$target"
    set_env_var "ARTEMIS_VECTOR_STORE_API_KEY" "$QDRANT_KEY" "$target"

    # Message broker
    set_env_var "ARTEMIS_REDIS_URL" "redis://redis:6379" "$target"
    set_env_var "REDIS_PASSWORD" "$REDIS_KEY" "$target"

    # Memory Bus
    set_env_var "ARTEMIS_MEMORY_WRITE_TIMEOUT_MS" "200" "$target"
    set_env_var "ARTEMIS_MEMORY_SYNC_TIMEOUT_MS" "300" "$target"
    set_env_var "ARTEMIS_MEMORY_CACHE_SIZE_MB" "100" "$target"
    set_env_var "ARTEMIS_MEMORY_QUEUE_MAX_BYTES" "10485760" "$target"

    # Embedding
    set_env_var "ARTEMIS_EMBEDDING_MODEL" "text-embedding-3-large" "$target"
    set_env_var "ARTEMIS_EMBEDDING_BATCH_SIZE" "100" "$target"
    set_env_var "ARTEMIS_EMBEDDING_API_KEY" "" "$target"

    # Governance
    set_env_var "ARTEMIS_APPROVAL_TIER1_ENABLED" "true" "$target"
    set_env_var "ARTEMIS_APPROVAL_TIER2_TIMEOUT_HOURS" "24" "$target"
    set_env_var "ARTEMIS_APPROVAL_TIER3_TIMEOUT_HOURS" "72" "$target"
    set_env_var "ARTEMIS_AUTO_ROLLBACK_ON_ERRORS" "true" "$target"
    set_env_var "ARTEMIS_AUTO_ROLLBACK_ERROR_THRESHOLD" "0.05" "$target"

    # Sandbox
    set_env_var "ARTEMIS_SANDBOX_VIOLATION_QUARANTINE_COUNT" "3" "$target"
    set_env_var "ARTEMIS_SANDBOX_VIOLATION_DECAY_DAYS" "30" "$target"

    # Security
    set_env_var "QDRANT_API_KEY" "$QDRANT_KEY" "$target"
    set_env_var "GRAFANA_PASSWORD" "$GRAFANA_KEY" "$target"

    # Monitoring
    set_env_var "ARTEMIS_PROMETHEUS_ENABLED" "true" "$target"
    set_env_var "ARTEMIS_METRICS_PORT" "9090" "$target"
    set_env_var "ARTEMIS_LOG_FORMAT" "json" "$target"
}

# Copy an example file to its target, apply all known key substitutions, and
# lock permissions. Pure no-op if the example is missing.
provision_env() {
    local example="$1" target="$2" label="$3"

    echo -e "${BLUE}>${NC} $label"
    echo "  example: $example"
    echo "  target:  $target"

    if [[ ! -f "$example" ]]; then
        echo -e "  ${YELLOW}skip${NC} — example not found"
        echo ""
        return 0
    fi

    if ! should_write "$target"; then
        echo -e "  ${YELLOW}skip${NC} — kept existing"
        echo ""
        return 0
    fi

    mkdir -p "$(dirname "$target")"
    cp "$example" "$target"

    # Apply substitutions. Each is a no-op when the placeholder is absent.
    set_value "your_secure_api_key_here" "$MCP_KEY" "$target"
    set_value "your_fastapi_api_key_here" "$FASTAPI_KEY" "$target"
    set_value "your_default_api_key_here" "$TS_KEY" "$target"

    if [[ "$target" == ".env" ]]; then
        add_root_deployment_env "$target"
    fi

    chmod 600 "$target"

    if git check-ignore "$target" >/dev/null 2>&1; then
        echo -e "  ${GREEN}ok${NC} written (chmod 600, git-ignored)"
    else
        echo -e "  ${RED}!!${NC} written but NOT git-ignored — fix .gitignore before committing"
    fi
    echo ""
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

echo "Artemis City — Secure Environment Setup"
echo "========================================"
echo ""

MCP_KEY="$(generate_key)"
FASTAPI_KEY="$(generate_key)"
TS_KEY="$(generate_key)"
REDIS_KEY="$(generate_key)"
QDRANT_KEY="$(generate_key)"
GRAFANA_KEY="$(generate_key)"

provision_env ".env.example"     ".env"     "Python core (.env)"
provision_env "app/api/.env.example" "app/api/.env" "TypeScript Express API (app/api/.env)"
provision_env "src/.env.example" "src/.env" "Memory-layer Python (src/.env)"
provision_env \
    "src/Artemis Agentic Memory Layer/.env.example" \
    "src/Artemis Agentic Memory Layer/.env" \
    "Memory-layer MCP server"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo -e "${GREEN}Setup complete.${NC}"
echo ""
echo "Generated keys were written only to files marked ok above."
echo "Skipped existing files were left unchanged; read the corresponding .env files locally if you need their current values."
echo ""
echo "Next steps:"
echo "  1. Add your Obsidian REST API key to .env:"
echo -e "     ${YELLOW}OBSIDIAN_API_KEY=<your key from Obsidian > Settings > Local REST API>${NC}"
echo "  2. Add OPENAI_API_KEY or ARTEMIS_EMBEDDING_API_KEY if you use hosted embeddings."
echo "  3. Set OBSIDIAN_VAULT_PATH for local runs if your vault isn't at <repo>/obsidian_vault."
echo "     The deployment default ARTEMIS_OBSIDIAN_VAULT_PATH is /data/vault for containers."
echo "  4. docker-compose.yml can now read REDIS_PASSWORD, QDRANT_API_KEY,"
echo "     GRAFANA_PASSWORD, and ARTEMIS_API_KEY_DEFAULT from the root .env."
echo "  5. If you skipped any existing .env, confirm MCP_API_KEY matches across"
echo "     consumers before starting cross-service workflows."
echo ""
echo "Security notes:"
echo "  - All written .env files are chmod 600."
echo "  - .gitignore covers .env at any depth — verified per file above."
echo "  - Re-running this script prompts before overwriting each file."
