#!/usr/bin/env bash
# ============================================
# ARTEMIS CITY - SECRET SETUP SCRIPT
# ============================================
# Scaffolds local .env files for each runtime surface in this repo.
# Usage: ./setup_secrets.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

OBSIDIAN_API_KEY_PLACEHOLDER="your_obsidian_api_key_here"
OBSIDIAN_VAULT_PATH_PLACEHOLDER="/absolute/path/to/your/obsidian/vault"
LEGAL_DATASET_PATH_PLACEHOLDER="/absolute/path/to/legal-judgements-en-ur-sd"
GENERATED_ON="$(date)"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  ARTEMIS CITY - SECURE ENV SETUP${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

if [ ! -d "src" ] || [ ! -f "README.md" ]; then
    echo -e "${RED}Error: run this script from the Artemis City repository root.${NC}"
    exit 1
fi

generate_key() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif command -v python3 >/dev/null 2>&1; then
        python3 -c "import secrets; print(secrets.token_hex(32))"
    elif command -v python >/dev/null 2>&1; then
        python -c "import secrets; print(secrets.token_hex(32))"
    elif command -v node >/dev/null 2>&1; then
        node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
    else
        echo -e "${RED}Error: install openssl, python, or node to generate secure keys.${NC}"
        exit 1
    fi
}

check_file() {
    local file="$1"

    if [ -f "$file" ]; then
        echo -e "${YELLOW}$file already exists.${NC}"
        read -r -p "Overwrite? (y/N): " reply
        if [[ ! "$reply" =~ ^[Yy]$ ]]; then
            echo "Skipping $file"
            return 1
        fi
    fi

    return 0
}

secure_file() {
    local file="$1"
    chmod 600 "$file"
    echo -e "${GREEN}Created $file with permissions 600${NC}"
}

verify_ignored() {
    local file="$1"

    if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        if git check-ignore "$file" >/dev/null 2>&1; then
            echo -e "${GREEN}$file is ignored by git${NC}"
        else
            echo -e "${YELLOW}Warning: $file may not be ignored by git${NC}"
        fi
    fi
}

MCP_API_KEY="$(generate_key)"
FASTAPI_API_KEY="$(generate_key)"
ARTEMIS_ADMIN_KEY="$(generate_key)"
ARTEMIS_PACKRAT_KEY="$(generate_key)"
ARTEMIS_COPILOT_KEY="$(generate_key)"
ARTEMIS_DAEMON_KEY="$(generate_key)"

echo -e "${CYAN}Generated local development keys.${NC}"
echo ""

echo -e "${BLUE}Step 1: root .env for shared local tooling${NC}"
if check_file ".env"; then
    cat > ".env" <<EOF
# ============================================
# ARTEMIS CITY - ROOT LOCAL ENV
# ============================================
# Generated by setup_secrets.sh on ${GENERATED_ON}
# Expected from repository root by Python dotenv users and local shells.
# Never commit this file.

# Local vault access
OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH_PLACEHOLDER}

# Python clients and demos
MCP_BASE_URL=http://localhost:3000
MCP_API_KEY=${MCP_API_KEY}

# MCP server defaults
PORT=3000
OBSIDIAN_BASE_URL=http://localhost:27124
OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY_PLACEHOLDER}
MCP_LOG_LEVEL=info
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:5173
API_RATE_LIMIT_WINDOW_MS=60000
API_RATE_LIMIT_MAX=100
API_RATE_LIMIT_MESSAGE="Too many requests, please try again later."
PROXY_TIMEOUT=5000
WORKER_POOL_SIZE=4
STORAGE_PATH=

# FastAPI dashboard
FASTAPI_API_KEY=${FASTAPI_API_KEY}
FASTAPI_CORS_ORIGINS=http://localhost:3000,http://localhost:4000

# Express web API server
API_PORT=4000
NODE_ENV=development
SKIP_AUTH=false
ARTEMIS_API_KEY_ARTEMIS=${ARTEMIS_ADMIN_KEY}:admin:read,write,delete,admin
ARTEMIS_API_KEY_PACKRAT=${ARTEMIS_PACKRAT_KEY}:service:read,write,search
ARTEMIS_API_KEY_COPILOT=${ARTEMIS_COPILOT_KEY}:assistant:read,search,query
ARTEMIS_API_KEY_DAEMON=${ARTEMIS_DAEMON_KEY}:service:read,write,system

# Optional legal summarization experiment
LEGAL_DATASET_PATH=${LEGAL_DATASET_PATH_PLACEHOLDER}
EOF
    secure_file ".env"
fi

echo ""
echo -e "${BLUE}Step 2: src/.env for Python memory/orchestrator code${NC}"
if [ -d "src" ] && check_file "src/.env"; then
    cat > "src/.env" <<EOF
# ============================================
# ARTEMIS CITY - PYTHON SRC ENV
# ============================================
# Generated by setup_secrets.sh on ${GENERATED_ON}
# Expected when running Python code from src/ or modules that call load_dotenv().
# Never commit this file.

OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH_PLACEHOLDER}
MCP_BASE_URL=http://localhost:3000
MCP_API_KEY=${MCP_API_KEY}
LEGAL_DATASET_PATH=${LEGAL_DATASET_PATH_PLACEHOLDER}
EOF
    secure_file "src/.env"
fi

echo ""
echo -e "${BLUE}Step 3: src/mcp-server/.env for the TypeScript MCP server${NC}"
if [ -d "src/mcp-server" ] && check_file "src/mcp-server/.env"; then
    cat > "src/mcp-server/.env" <<EOF
# ============================================
# ARTEMIS CITY - MCP SERVER ENV
# ============================================
# Generated by setup_secrets.sh on ${GENERATED_ON}
# Expected when running from src/mcp-server with npm run dev/start.
# Never commit this file.

PORT=3000
MCP_API_KEY=${MCP_API_KEY}
OBSIDIAN_BASE_URL=http://localhost:27124
OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY_PLACEHOLDER}
OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH_PLACEHOLDER}
MCP_LOG_LEVEL=info
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:5173
API_RATE_LIMIT_WINDOW_MS=60000
API_RATE_LIMIT_MAX=100
API_RATE_LIMIT_MESSAGE="Too many requests, please try again later."
PROXY_TIMEOUT=5000
WORKER_POOL_SIZE=4
STORAGE_PATH=
EOF
    secure_file "src/mcp-server/.env"
fi

echo ""
echo -e "${BLUE}Step 4: web/api/.env for Express and FastAPI API surfaces${NC}"
if [ -d "web/api" ] && check_file "web/api/.env"; then
    cat > "web/api/.env" <<EOF
# ============================================
# ARTEMIS CITY - WEB API ENV
# ============================================
# Generated by setup_secrets.sh on ${GENERATED_ON}
# The Express and FastAPI code reads process environment. Source this file
# or use your process manager's env-file support when running web/api.
# Never commit this file.

API_PORT=4000
NODE_ENV=development
SKIP_AUTH=false
MCP_API_KEY=${MCP_API_KEY}
OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH_PLACEHOLDER}
FASTAPI_API_KEY=${FASTAPI_API_KEY}
FASTAPI_CORS_ORIGINS=http://localhost:3000,http://localhost:4000
ARTEMIS_API_KEY_ARTEMIS=${ARTEMIS_ADMIN_KEY}:admin:read,write,delete,admin
ARTEMIS_API_KEY_PACKRAT=${ARTEMIS_PACKRAT_KEY}:service:read,write,search
ARTEMIS_API_KEY_COPILOT=${ARTEMIS_COPILOT_KEY}:assistant:read,search,query
ARTEMIS_API_KEY_DAEMON=${ARTEMIS_DAEMON_KEY}:service:read,write,system
EOF
    secure_file "web/api/.env"
fi

echo ""
echo -e "${BLUE}Step 5: mcp-server/.env for the Docker Compose MCP server wrapper${NC}"
if [ -d "mcp-server" ] && check_file "mcp-server/.env"; then
    cat > "mcp-server/.env" <<EOF
# ============================================
# ARTEMIS CITY - DOCKER MCP SERVER ENV
# ============================================
# Generated by setup_secrets.sh on ${GENERATED_ON}
# Expected by mcp-server/docker-compose.yml when run from mcp-server/.
# Never commit this file.

PORT=3000
MCP_API_KEY=${MCP_API_KEY}
OBSIDIAN_BASE_URL=http://host.docker.internal:27124
OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY_PLACEHOLDER}
EOF
    secure_file "mcp-server/.env"
fi

echo ""
echo -e "${BLUE}Step 6: verifying git ignore protection${NC}"
verify_ignored ".env"
verify_ignored "src/.env"
verify_ignored "src/mcp-server/.env"
verify_ignored "web/api/.env"
verify_ignored "mcp-server/.env"

echo ""
echo -e "${GREEN}Setup complete.${NC}"
echo ""
echo "Manual values still required:"
echo -e "  ${YELLOW}OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY_PLACEHOLDER}${NC}"
echo -e "  ${YELLOW}OBSIDIAN_VAULT_PATH=${OBSIDIAN_VAULT_PATH_PLACEHOLDER}${NC}"
echo -e "  ${YELLOW}LEGAL_DATASET_PATH=${LEGAL_DATASET_PATH_PLACEHOLDER}${NC} (only for the legal summarization experiment)"
echo ""
echo "Environment index:"
echo "  docs/ENVIRONMENT_INDEX.md"
echo ""
echo "The same MCP_API_KEY was written to each generated env file so clients and servers agree."
