global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: production

scrape_configs:
  - job_name: "artemis-kernel"
    static_configs:
      - targets:
          - "kernel:8000"
    metrics_path: "/metrics"

  - job_name: "artemis-express-api"
    static_configs:
      - targets:
          - "express-api:4000"
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
