/**
 * Shared client-side route contract.
 *
 * Page components should import destinations from this module instead of
 * rebuilding URL strings. Route parameters are encoded here so identifiers
 * remain data, not path syntax.
 */

export const routeSegments = {
  dashboard: '',
  tasks: 'tasks',
  taskId: ':taskId',
  taskActivity: 'activity',
  reports: 'reports',
  reportFilename: ':filename',
  agents: 'agents',
  database: 'database',
  executor: 'executor',
  monitoring: 'monitoring',
} as const;

export const routePaths = {
  dashboard: '/',
  tasks: `/${routeSegments.tasks}`,
  reports: `/${routeSegments.reports}`,
  agents: `/${routeSegments.agents}`,
  database: `/${routeSegments.database}`,
  executor: `/${routeSegments.executor}`,
  monitoring: `/${routeSegments.monitoring}`,
  task: (taskId: string) => `/${routeSegments.tasks}/${encodeURIComponent(taskId)}`,
  taskActivity: (taskId: string) =>
    `/${routeSegments.tasks}/${encodeURIComponent(taskId)}/${routeSegments.taskActivity}`,
  report: (filename: string) =>
    `/${routeSegments.reports}/${encodeURIComponent(filename)}`,
} as const;

// Reports generated by the orchestrator use _artifact_component(), which
// permits alphanumeric characters, '-', '_', and '.'. Keep the same
// constraint at the UI boundary and cap the value at a single filename's
// maximum length. The API remains the authoritative containment boundary.
const SAFE_REPORT_FILENAME = /^(?=.{1,255}$)[\p{L}\p{N}-][\p{L}\p{N}._-]*\.md$/u;

export const isSafeReportFilename = (filename: string): boolean =>
  typeof filename === 'string' && SAFE_REPORT_FILENAME.test(filename);
