name: Dependency Submission

on:
  push:
    branches: [ dev, prod , staging ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # choose version your deps support

      - name: Submit dependency graph
        uses: actions/dependency-submission-action@v3       
        with:
          # Adjust to your files
          manifest-path: |
            pyproject.toml
            requirements.txt
            requirements-dev.txt