name: Dependency Submission

on:
  push:
    branches: [ dev, prod , staging ]
  pull_request:   
    branches: [ dev, prod , staging ]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  submit-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:    
      - name: Submit dependency graph
        uses: actions/dependency-submission-action@v4
        with:
          # Adjust to your files
          manifest-path: |
            pyproject.toml
            requirements.txt
            requirements-dev.txt